### ISSUE TITLE
Doom flake causes infinite recursion

### ISSUE THREAD

**Issue by pimeys** [vlaci/nix-doom-emacs#157]
Hi. Sorry, if I ask a bit dumb questions, I'm still learning nix and flakes. But, I'm building a new flake configuration from the ground up, and following the README here, I import the module in my `home.nix`:

https://github.com/pimeys/system-flake/blob/main/home.nix#L4

And define the flake in my `flake.nix`:

https://github.com/pimeys/system-flake/blob/main/flake.nix#L11

Now, when I run `nix flake check`, I'll get an infinite recursion, that will solve itself if I remove the import for the doom flake in my `home.nix`. If I define the import in `flake.nix` directly, it works. But I'd like to keep my home configuration in a separate file.

I think I have some idea what might be going wrong here, that the `nix-doom-emacs` variable in `home.nix` is not the same as when called in the `flake.nix`. I just can't find a way to refactor this to a working condition.

**Comment by pimeys** [comment]
Nevermind, got it working after a few days of research. https://github.com/pimeys/system-flake/commit/072930e32a7561ab2002c67effdbccadebd6c00c

**Comment by tim-hilt** [comment]
I actually am in a pretty similar state as you were when opening this issue :D Your solution made my config rebuild; thanks for that. Now that you've been working with Nix for a bit longer, can you explain to me why the initial solution didn't work?

**Comment by vlaci** [comment]
In the above case the infinite recursion is IMHO caused by this line:
https://github.com/pimeys/system-flake/commit/072930e32a7561ab2002c67effdbccadebd6c00c#diff-31229fa992b403d35ed9d8652247285873be74fb3210d541767d0cf74a231371L1

by default only some well-known arguments are passed to NixOS modules (lib, options, config, pkgs, modulesPath the ones I am aware of). Home-manager does the same.

Recent home-manager revisions have [`home-manager.extraSpecialArgs`](https://nix-community.github.io/home-manager/nixos-options.html#nixos-opt-home-manager.extraSpecialArgs) option where you can add additional arguments which get passed to modules.

**Comment by addy419** [comment]
@tim-hilt I was in the same position. After searching for a while, I was actually able to find the solution: https://discourse.nixos.org/t/flakes-idiomatic-way-to-pass-inputs-to-configuration-nix/12379/2
