### ISSUE TITLE
Adding to home-manager

### ISSUE THREAD

**Issue by happysalada** [vlaci/nix-doom-emacs#65]
I have no idea how easy that is, but how about adding doom-emacs to home manager?
https://github.com/nix-community/home-manager/tree/master/modules/programs

I have also spotted this doom config in the wild.
https://github.com/burke/b/blob/f94e0b653d28b290552ab9a7069a71b59d54f80c/etc/nix/home/modules/doom.nix
It might be a good base to add an entry into home-manager

Just a thought

**Comment by vlaci** [comment]
I have thought about it but I'd like to first add a module in this source tree for others to experiment with. It is in fact quite easy to add extension modules to home-manager and nixos. The only reason I have not started experimenting with it is the lack of free time to experiment with it. In order to be usable for others it should be easy to configure and also shouldn't have too opinionated defaults. Most home-manager modules tend to have extensive configuration options so that most users don't need to write their native configuration files by hand at all. I don't know if an emacs configuration should ever get down on that path (e.g. having `init.el` and such autogenerated from the module options).

I also have a module included in my private configuration: https://github.com/vlaci/blox/blob/develop/modules/home/doom-emacs/default.nix.

**Comment by vlaci** [comment]
There is a new flake branch where I experiment with `flake.nix support. It contains a home-manager modules as well.

https://github.com/vlaci/nix-doom-emacs/blob/flake/flake.nix

**Comment by happysalada** [comment]
Very nice!

**Comment by vlaci** [comment]
Implemented by #77
